/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BadgeMilestoneResponse {
  'badges' : Array<MilestoneBadge>,
  'milestones' : MilestoneProgress,
}
export interface CanonicalPartnerRitualStatus {
  'partnerBComplete' : boolean,
  'partnerA' : UserId,
  'partnerB' : UserId,
  'partnerAComplete' : boolean,
}
export interface ChallengeStats {
  'completedChallenges' : bigint,
  'progressPercent' : number,
  'totalChallenges' : bigint,
}
export interface CombinedQuizResultState {
  'callerResults' : [] | [LoveLanguagesQuizResult],
  'partnerCompleted' : boolean,
  'partnerResults' : [] | [LoveLanguagesQuizResult],
  'callerCompleted' : boolean,
}
export interface DailyRitualInput {
  'text' : [] | [string],
  'emoji' : [] | [string],
  'photoId' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface GardenProgress {
  'xp' : XP,
  'unlockedPlant' : [] | [Plant],
  'level' : bigint,
  'hasAvailableRewards' : boolean,
  'streakMilestones' : Array<Plant>,
  'badgeAchievements' : Array<Plant>,
  'isComplete' : boolean,
  'levelProgress' : number,
}
export interface InsighsDataExtendedResponse {
  'challengeStats' : ChallengeStats,
  'mostFrequentLoveLanguage' : string,
  'last14DayTrend' : Array<boolean>,
  'recentCompletionRate' : number,
  'badges' : Array<MilestoneBadge>,
  'quizOverlapScore' : number,
  'last30DayTrend' : Array<boolean>,
  'currentHarmony' : number,
  'harmonyTrend' : Array<number>,
  'longestStreak' : bigint,
  'challengeCompletionRate' : number,
  'averageHarmony' : number,
  'currentStreak' : bigint,
  'milestones' : MilestoneProgress,
}
export interface LoveGarden {
  'xp' : XP,
  'level' : bigint,
  'streakMilestones' : Array<Plant>,
  'badgeAchievements' : Array<Plant>,
  'isComplete' : boolean,
}
export type LoveLanguage = { 'qualityTime' : null } |
  { 'receivingGifts' : null } |
  { 'actsOfService' : null } |
  { 'wordsOfAffirmation' : null } |
  { 'physicalTouch' : null };
export interface LoveLanguageRanking {
  'score' : number,
  'language' : LoveLanguage,
}
export interface LoveLanguagesQuizResult {
  'rankings' : Array<LoveLanguageRanking>,
  'completionTime' : Time,
  'userId' : UserId,
}
export interface MilestoneBadge {
  'name' : string,
  'dateAchieved' : Time,
  'isUnlocked' : boolean,
}
export interface MilestoneProgress {
  'hundredDayUnlocked' : boolean,
  'thirtyDayUnlocked' : boolean,
  'sevenDayUnlocked' : boolean,
  'harmonyEliteUnlocked' : boolean,
}
export type PairingResult = { 'ok' : null } |
  { 'err' : string };
export interface PartnerQuizState {
  'partnerCompleted' : boolean,
  'partnerResults' : [] | [LoveLanguagesQuizResult],
}
export interface Plant {
  'name' : string,
  'description' : string,
  'milestone' : string,
  'isUnlocked' : boolean,
  'xpRequired' : XP,
}
export interface RewardXPResult {
  'level' : bigint,
  'newXP' : bigint,
  'previousXP' : bigint,
}
export interface RitualEntryView {
  'responses' : Array<RitualResponse>,
  'loveLanguageFocus' : [] | [LoveLanguage],
  'date' : bigint,
  'prompt' : RitualPrompt,
}
export interface RitualPrompt {
  'id' : bigint,
  'text' : string,
  'loveLanguage' : [] | [LoveLanguage],
}
export interface RitualResponse {
  'userId' : UserId,
  'text' : [] | [string],
  'emoji' : [] | [string],
  'photoId' : [] | [string],
}
export interface SharedPhoto {
  'id' : string,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'name' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type XP = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPairingCode' : ActorMethod<[bigint], [] | [Principal]>,
  'clearLoveLanguagesQuizResults' : ActorMethod<[], undefined>,
  'completePairing' : ActorMethod<[bigint], PairingResult>,
  'completeWeeklyChallengeWithProof' : ActorMethod<
    [[] | [ExternalBlob]],
    undefined
  >,
  'confirmWeeklyChallengeWithoutProof' : ActorMethod<[], undefined>,
  'createGarden' : ActorMethod<[], undefined>,
  'createPairingCode' : ActorMethod<[], bigint>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'fetchPrompts' : ActorMethod<[], Array<RitualPrompt>>,
  'getAllBadges' : ActorMethod<[], Array<[UserId, Array<string>]>>,
  'getBadgeMilestones' : ActorMethod<[], BadgeMilestoneResponse>,
  'getBadges' : ActorMethod<[], Array<string>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCombinedQuizResultState' : ActorMethod<
    [],
    [] | [CombinedQuizResultState]
  >,
  'getDailyRitual' : ActorMethod<[], [] | [RitualPrompt]>,
  'getInsightsData' : ActorMethod<[], InsighsDataExtendedResponse>,
  'getLoveGarden' : ActorMethod<[], LoveGarden>,
  'getLoveGardenProgress' : ActorMethod<[], GardenProgress>,
  'getLoveLanguageQuizResult' : ActorMethod<[], [] | [LoveLanguagesQuizResult]>,
  'getPartnerQuizState' : ActorMethod<[UserId], PartnerQuizState>,
  'getPhoto' : ActorMethod<[string], [] | [SharedPhoto]>,
  'getPhotosByUser' : ActorMethod<[UserId], Array<SharedPhoto>>,
  'getPromptsByLoveLanguage' : ActorMethod<[LoveLanguage], Array<RitualPrompt>>,
  'getRitualHistory' : ActorMethod<[bigint], Array<RitualEntryView>>,
  'getRitualStatus' : ActorMethod<[], [] | [CanonicalPartnerRitualStatus]>,
  'getXP' : ActorMethod<[], bigint>,
  'getXPForAllUsers' : ActorMethod<[], Array<[UserId, bigint]>>,
  'initializeUserProfile' : ActorMethod<[string, [] | [UserId]], UserId>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rewardXP' : ActorMethod<[bigint], RewardXPResult>,
  'saveLoveLanguageQuizResults' : ActorMethod<
    [LoveLanguagesQuizResult],
    undefined
  >,
  'submitRitualResponse' : ActorMethod<[DailyRitualInput], undefined>,
  'unlockPlant' : ActorMethod<[string], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];