/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'partnerId' : IDL.Opt(IDL.Principal),
});
export const RitualPrompt = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const EntryStatus = IDL.Variant({
  'complete' : IDL.Null,
  'waitingForPartner' : IDL.Null,
});
export const RitualResponse = IDL.Record({
  'userId' : UserId,
  'text' : IDL.Opt(IDL.Text),
  'emoji' : IDL.Opt(IDL.Text),
});
export const GetDailyRitualResponse = IDL.Record({
  'status' : EntryStatus,
  'responses' : IDL.Vec(RitualResponse),
  'harmonyMeter' : IDL.Float64,
  'prompt' : RitualPrompt,
  'streakCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const SharedPhoto = IDL.Record({
  'id' : IDL.Text,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'timestamp' : Time,
});
export const PartnerRitualStatus = IDL.Record({
  'partnerBComplete' : IDL.Bool,
  'partnerAComplete' : IDL.Bool,
});
export const DailyRitualInput = IDL.Record({
  'text' : IDL.Opt(IDL.Text),
  'emoji' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPartner' : IDL.Func([UserId], [], []),
  'checkPairingCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], []),
  'completePairing' : IDL.Func([IDL.Nat], [], []),
  'createPairingCode' : IDL.Func([], [IDL.Nat], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyRitual' : IDL.Func([], [IDL.Opt(RitualPrompt)], ['query']),
  'getDailyRitualWithStats' : IDL.Func([], [GetDailyRitualResponse], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [IDL.Opt(SharedPhoto)], ['query']),
  'getPhotosByUser' : IDL.Func([UserId], [IDL.Vec(SharedPhoto)], ['query']),
  'getRitualStatus' : IDL.Func([], [PartnerRitualStatus], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'initPrompts' : IDL.Func([], [], []),
  'initializeUserProfile' : IDL.Func([IDL.Text, IDL.Opt(UserId)], [UserId], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRitualResponse' : IDL.Func([DailyRitualInput], [], []),
  'uploadPhoto' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'partnerId' : IDL.Opt(IDL.Principal),
  });
  const RitualPrompt = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const EntryStatus = IDL.Variant({
    'complete' : IDL.Null,
    'waitingForPartner' : IDL.Null,
  });
  const RitualResponse = IDL.Record({
    'userId' : UserId,
    'text' : IDL.Opt(IDL.Text),
    'emoji' : IDL.Opt(IDL.Text),
  });
  const GetDailyRitualResponse = IDL.Record({
    'status' : EntryStatus,
    'responses' : IDL.Vec(RitualResponse),
    'harmonyMeter' : IDL.Float64,
    'prompt' : RitualPrompt,
    'streakCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const SharedPhoto = IDL.Record({
    'id' : IDL.Text,
    'owner' : UserId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'timestamp' : Time,
  });
  const PartnerRitualStatus = IDL.Record({
    'partnerBComplete' : IDL.Bool,
    'partnerAComplete' : IDL.Bool,
  });
  const DailyRitualInput = IDL.Record({
    'text' : IDL.Opt(IDL.Text),
    'emoji' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPartner' : IDL.Func([UserId], [], []),
    'checkPairingCode' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], []),
    'completePairing' : IDL.Func([IDL.Nat], [], []),
    'createPairingCode' : IDL.Func([], [IDL.Nat], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyRitual' : IDL.Func([], [IDL.Opt(RitualPrompt)], ['query']),
    'getDailyRitualWithStats' : IDL.Func(
        [],
        [GetDailyRitualResponse],
        ['query'],
      ),
    'getPhoto' : IDL.Func([IDL.Text], [IDL.Opt(SharedPhoto)], ['query']),
    'getPhotosByUser' : IDL.Func([UserId], [IDL.Vec(SharedPhoto)], ['query']),
    'getRitualStatus' : IDL.Func([], [PartnerRitualStatus], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'initPrompts' : IDL.Func([], [], []),
    'initializeUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(UserId)],
        [UserId],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRitualResponse' : IDL.Func([DailyRitualInput], [], []),
    'uploadPhoto' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };