/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyRitualInput {
  'text' : [] | [string],
  'emoji' : [] | [string],
}
export type EntryStatus = { 'complete' : null } |
  { 'waitingForPartner' : null };
export type ExternalBlob = Uint8Array;
export interface GetDailyRitualResponse {
  'status' : EntryStatus,
  'responses' : Array<RitualResponse>,
  'harmonyMeter' : number,
  'prompt' : RitualPrompt,
  'streakCount' : bigint,
}
export interface PartnerRitualStatus {
  'partnerBComplete' : boolean,
  'partnerAComplete' : boolean,
}
export interface RitualPrompt { 'id' : bigint, 'text' : string }
export interface RitualResponse {
  'userId' : UserId,
  'text' : [] | [string],
  'emoji' : [] | [string],
}
export interface SharedPhoto {
  'id' : string,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'name' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'partnerId' : [] | [Principal] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPartner' : ActorMethod<[UserId], undefined>,
  'checkPairingCode' : ActorMethod<[bigint], [] | [Principal]>,
  'completePairing' : ActorMethod<[bigint], undefined>,
  'createPairingCode' : ActorMethod<[], bigint>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyRitual' : ActorMethod<[], [] | [RitualPrompt]>,
  'getDailyRitualWithStats' : ActorMethod<[], GetDailyRitualResponse>,
  'getPhoto' : ActorMethod<[string], [] | [SharedPhoto]>,
  'getPhotosByUser' : ActorMethod<[UserId], Array<SharedPhoto>>,
  'getRitualStatus' : ActorMethod<[], PartnerRitualStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'initPrompts' : ActorMethod<[], undefined>,
  'initializeUserProfile' : ActorMethod<[string, [] | [UserId]], UserId>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRitualResponse' : ActorMethod<[DailyRitualInput], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];