/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BadgeMilestoneResponse {
  'badges' : Array<MilestoneBadge>,
  'milestones' : MilestoneProgress,
}
export interface CanonicalPartnerRitualStatus {
  'partnerBComplete' : boolean,
  'partnerA' : UserId,
  'partnerB' : UserId,
  'partnerAComplete' : boolean,
}
export interface ChallengeStats {
  'completedChallenges' : bigint,
  'progressPercent' : number,
  'totalChallenges' : bigint,
}
export interface CombinedQuizResultState {
  'callerResults' : [] | [LoveLanguagesQuizResult],
  'partnerCompleted' : boolean,
  'partnerResults' : [] | [LoveLanguagesQuizResult],
  'callerCompleted' : boolean,
}
export interface DailyRitualInput {
  'text' : [] | [string],
  'emoji' : [] | [string],
  'photoId' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface InsighsDataExtendedResponse {
  'challengeStats' : ChallengeStats,
  'mostFrequentLoveLanguage' : string,
  'last14DayTrend' : Array<boolean>,
  'recentCompletionRate' : number,
  'badges' : Array<MilestoneBadge>,
  'quizOverlapScore' : number,
  'last30DayTrend' : Array<boolean>,
  'currentHarmony' : number,
  'harmonyTrend' : Array<number>,
  'longestStreak' : bigint,
  'challengeCompletionRate' : number,
  'averageHarmony' : number,
  'currentStreak' : bigint,
  'milestones' : MilestoneProgress,
}
export type LoveLanguage = { 'qualityTime' : null } |
  { 'receivingGifts' : null } |
  { 'actsOfService' : null } |
  { 'wordsOfAffirmation' : null } |
  { 'physicalTouch' : null };
export interface LoveLanguageRanking {
  'score' : number,
  'language' : LoveLanguage,
}
export interface LoveLanguagesQuizResult {
  'rankings' : Array<LoveLanguageRanking>,
  'completionTime' : Time,
  'userId' : UserId,
}
export interface MilestoneBadge {
  'name' : string,
  'dateAchieved' : Time,
  'isUnlocked' : boolean,
}
export interface MilestoneProgress {
  'hundredDayUnlocked' : boolean,
  'thirtyDayUnlocked' : boolean,
  'sevenDayUnlocked' : boolean,
  'harmonyEliteUnlocked' : boolean,
}
export type PairingResult = { 'ok' : null } |
  { 'err' : string };
export interface PartnerQuizState {
  'partnerCompleted' : boolean,
  'partnerResults' : [] | [LoveLanguagesQuizResult],
}
export interface RitualEntryView {
  'responses' : Array<RitualResponse>,
  'loveLanguageFocus' : [] | [LoveLanguage],
  'date' : bigint,
  'prompt' : RitualPrompt,
}
export interface RitualPrompt {
  'id' : bigint,
  'text' : string,
  'loveLanguage' : [] | [LoveLanguage],
}
export interface RitualResponse {
  'userId' : UserId,
  'text' : [] | [string],
  'emoji' : [] | [string],
  'photoId' : [] | [string],
}
export interface SharedPhoto {
  'id' : string,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'name' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'partnerId' : [] | [Principal],
  'isFirstUser' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkPairingCode' : ActorMethod<[bigint], [] | [Principal]>,
  'clearLoveLanguagesQuizResults' : ActorMethod<[], undefined>,
  'completePairing' : ActorMethod<[bigint], PairingResult>,
  'createPairingCode' : ActorMethod<[], bigint>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'fetchPrompts' : ActorMethod<[], Array<RitualPrompt>>,
  'getBadgeMilestones' : ActorMethod<[], BadgeMilestoneResponse>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCombinedQuizResultState' : ActorMethod<
    [],
    [] | [CombinedQuizResultState]
  >,
  'getDailyRitual' : ActorMethod<[], [] | [RitualPrompt]>,
  'getInsightsData' : ActorMethod<[], InsighsDataExtendedResponse>,
  'getLoveLanguageQuizResult' : ActorMethod<[], [] | [LoveLanguagesQuizResult]>,
  'getPartnerQuizState' : ActorMethod<[UserId], PartnerQuizState>,
  'getPhoto' : ActorMethod<[string], [] | [SharedPhoto]>,
  'getPhotosByUser' : ActorMethod<[UserId], Array<SharedPhoto>>,
  'getPromptsByLoveLanguage' : ActorMethod<[LoveLanguage], Array<RitualPrompt>>,
  'getRitualHistory' : ActorMethod<[bigint], Array<RitualEntryView>>,
  'getRitualStatus' : ActorMethod<[], [] | [CanonicalPartnerRitualStatus]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'initializeUserProfile' : ActorMethod<[string, [] | [UserId]], UserId>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLoveLanguageQuizResults' : ActorMethod<
    [LoveLanguagesQuizResult],
    undefined
  >,
  'submitRitualResponse' : ActorMethod<[DailyRitualInput], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];