/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CoupleProgress = IDL.Record({
  'pointsForNextLevel' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'levelThresholds' : IDL.Vec(IDL.Nat),
  'pointsToNextLevel' : IDL.Nat,
});
export const LoveLanguage = IDL.Variant({
  'qualityTime' : IDL.Null,
  'receivingGifts' : IDL.Null,
  'actsOfService' : IDL.Null,
  'wordsOfAffirmation' : IDL.Null,
  'physicalTouch' : IDL.Null,
});
export const RitualPrompt = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'loveLanguage' : IDL.Opt(LoveLanguage),
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'partnerId' : IDL.Opt(UserId),
  'isFirstUser' : IDL.Bool,
});
export const LoveLanguageRanking = IDL.Record({
  'score' : IDL.Float64,
  'language' : LoveLanguage,
});
export const Time = IDL.Int;
export const LoveLanguagesQuizResult = IDL.Record({
  'rankings' : IDL.Vec(LoveLanguageRanking),
  'completionTime' : Time,
  'userId' : UserId,
});
export const CombinedQuizResultState = IDL.Record({
  'callerResults' : IDL.Opt(LoveLanguagesQuizResult),
  'partnerCompleted' : IDL.Bool,
  'partnerResults' : IDL.Opt(LoveLanguagesQuizResult),
  'callerCompleted' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'calculateLevelPointsNonAuth' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [CoupleProgress],
      ['query'],
    ),
  'fetchPrompts' : IDL.Func([], [IDL.Vec(RitualPrompt)], ['query']),
  'getBadges' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCombinedQuizResultState' : IDL.Func(
      [],
      [IDL.Opt(CombinedQuizResultState)],
      ['query'],
    ),
  'getCoupleProgress' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat],
      [CoupleProgress],
      ['query'],
    ),
  'getLevelThresholds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getXP' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CoupleProgress = IDL.Record({
    'pointsForNextLevel' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'levelThresholds' : IDL.Vec(IDL.Nat),
    'pointsToNextLevel' : IDL.Nat,
  });
  const LoveLanguage = IDL.Variant({
    'qualityTime' : IDL.Null,
    'receivingGifts' : IDL.Null,
    'actsOfService' : IDL.Null,
    'wordsOfAffirmation' : IDL.Null,
    'physicalTouch' : IDL.Null,
  });
  const RitualPrompt = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'loveLanguage' : IDL.Opt(LoveLanguage),
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'partnerId' : IDL.Opt(UserId),
    'isFirstUser' : IDL.Bool,
  });
  const LoveLanguageRanking = IDL.Record({
    'score' : IDL.Float64,
    'language' : LoveLanguage,
  });
  const Time = IDL.Int;
  const LoveLanguagesQuizResult = IDL.Record({
    'rankings' : IDL.Vec(LoveLanguageRanking),
    'completionTime' : Time,
    'userId' : UserId,
  });
  const CombinedQuizResultState = IDL.Record({
    'callerResults' : IDL.Opt(LoveLanguagesQuizResult),
    'partnerCompleted' : IDL.Bool,
    'partnerResults' : IDL.Opt(LoveLanguagesQuizResult),
    'callerCompleted' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'calculateLevelPointsNonAuth' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [CoupleProgress],
        ['query'],
      ),
    'fetchPrompts' : IDL.Func([], [IDL.Vec(RitualPrompt)], ['query']),
    'getBadges' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCombinedQuizResultState' : IDL.Func(
        [],
        [IDL.Opt(CombinedQuizResultState)],
        ['query'],
      ),
    'getCoupleProgress' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat],
        [CoupleProgress],
        ['query'],
      ),
    'getLevelThresholds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getXP' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };