/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CombinedQuizResultState {
  'callerResults' : [] | [LoveLanguagesQuizResult],
  'partnerCompleted' : boolean,
  'partnerResults' : [] | [LoveLanguagesQuizResult],
  'callerCompleted' : boolean,
}
export interface CoupleProgress {
  'pointsForNextLevel' : bigint,
  'currentLevel' : bigint,
  'totalPoints' : bigint,
  'levelThresholds' : Array<bigint>,
  'pointsToNextLevel' : bigint,
}
export type LoveLanguage = { 'qualityTime' : null } |
  { 'receivingGifts' : null } |
  { 'actsOfService' : null } |
  { 'wordsOfAffirmation' : null } |
  { 'physicalTouch' : null };
export interface LoveLanguageRanking {
  'score' : number,
  'language' : LoveLanguage,
}
export interface LoveLanguagesQuizResult {
  'rankings' : Array<LoveLanguageRanking>,
  'completionTime' : Time,
  'userId' : UserId,
}
export interface RitualPrompt {
  'id' : bigint,
  'text' : string,
  'loveLanguage' : [] | [LoveLanguage],
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'partnerId' : [] | [UserId],
  'isFirstUser' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'calculateLevelPointsNonAuth' : ActorMethod<
    [bigint, bigint, bigint],
    CoupleProgress
  >,
  'fetchPrompts' : ActorMethod<[], Array<RitualPrompt>>,
  'getBadges' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCombinedQuizResultState' : ActorMethod<
    [],
    [] | [CombinedQuizResultState]
  >,
  'getCoupleProgress' : ActorMethod<
    [Principal, bigint, bigint, bigint],
    CoupleProgress
  >,
  'getLevelThresholds' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getXP' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];