/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SharedPhoto {
    id: string;
    owner: UserId;
    blob: ExternalBlob;
    name: string;
    timestamp: Time;
}
export interface LoveLanguagesQuizResult {
    rankings: Array<LoveLanguageRanking>;
    completionTime: Time;
    userId: UserId;
}
export interface InsighsDataExtendedResponse {
    challengeStats: ChallengeStats;
    mostFrequentLoveLanguage: string;
    last14DayTrend: Array<boolean>;
    recentCompletionRate: number;
    badges: Array<MilestoneBadge>;
    quizOverlapScore: number;
    last30DayTrend: Array<boolean>;
    currentHarmony: number;
    harmonyTrend: Array<number>;
    longestStreak: bigint;
    challengeCompletionRate: number;
    averageHarmony: number;
    currentStreak: bigint;
    milestones: MilestoneProgress;
}
export type Time = bigint;
export interface RitualResponse {
    userId: UserId;
    text?: string;
    emoji?: string;
    photoId?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RitualEntryView {
    responses: Array<RitualResponse>;
    loveLanguageFocus?: LoveLanguage;
    date: bigint;
    prompt: RitualPrompt;
}
export interface DailyRitualInput {
    text?: string;
    emoji?: string;
    photoId?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LoveLanguageRanking {
    score: number;
    language: LoveLanguage;
}
export interface RitualPrompt {
    id: bigint;
    text: string;
    loveLanguage?: LoveLanguage;
}
export interface CombinedQuizResultState {
    callerResults?: LoveLanguagesQuizResult;
    partnerCompleted: boolean;
    partnerResults?: LoveLanguagesQuizResult;
    callerCompleted: boolean;
}
export interface ChallengeStats {
    completedChallenges: bigint;
    progressPercent: number;
    totalChallenges: bigint;
}
export interface PartnerQuizState {
    partnerCompleted: boolean;
    partnerResults?: LoveLanguagesQuizResult;
}
export type UserId = Principal;
export interface CanonicalPartnerRitualStatus {
    partnerBComplete: boolean;
    partnerA: UserId;
    partnerB: UserId;
    partnerAComplete: boolean;
}
export interface BadgeMilestoneResponse {
    badges: Array<MilestoneBadge>;
    milestones: MilestoneProgress;
}
export type PairingResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface MilestoneBadge {
    name: string;
    dateAchieved: Time;
    isUnlocked: boolean;
}
export interface MilestoneProgress {
    hundredDayUnlocked: boolean;
    thirtyDayUnlocked: boolean;
    sevenDayUnlocked: boolean;
    harmonyEliteUnlocked: boolean;
}
export interface UserProfile {
    name: string;
    role: UserRole;
    partnerId?: Principal;
    isFirstUser: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum LoveLanguage {
    qualityTime = "qualityTime",
    receivingGifts = "receivingGifts",
    actsOfService = "actsOfService",
    wordsOfAffirmation = "wordsOfAffirmation",
    physicalTouch = "physicalTouch"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    checkPairingCode(code: bigint): Promise<Principal | null>;
    clearLoveLanguagesQuizResults(): Promise<void>;
    completePairing(code: bigint): Promise<PairingResult>;
    createPairingCode(): Promise<bigint>;
    deletePhoto(id: string): Promise<void>;
    fetchPrompts(): Promise<Array<RitualPrompt>>;
    getBadgeMilestones(): Promise<BadgeMilestoneResponse>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCombinedQuizResultState(): Promise<CombinedQuizResultState | null>;
    getDailyRitual(): Promise<RitualPrompt | null>;
    getInsightsData(): Promise<InsighsDataExtendedResponse>;
    getLoveLanguageQuizResult(): Promise<LoveLanguagesQuizResult | null>;
    getPartnerQuizState(partnerId: UserId): Promise<PartnerQuizState>;
    getPhoto(id: string): Promise<SharedPhoto | null>;
    getPhotosByUser(user: UserId): Promise<Array<SharedPhoto>>;
    getPromptsByLoveLanguage(language: LoveLanguage): Promise<Array<RitualPrompt>>;
    getRitualHistory(limit: bigint): Promise<Array<RitualEntryView>>;
    getRitualStatus(): Promise<CanonicalPartnerRitualStatus | null>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    initializeUserProfile(name: string, partnerId: UserId | null): Promise<UserId>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveLoveLanguageQuizResults(result: LoveLanguagesQuizResult): Promise<void>;
    submitRitualResponse(input: DailyRitualInput): Promise<void>;
    uploadPhoto(blob: ExternalBlob, name: string): Promise<string>;
}
import type { CanonicalPartnerRitualStatus as _CanonicalPartnerRitualStatus, CombinedQuizResultState as _CombinedQuizResultState, DailyRitualInput as _DailyRitualInput, ExternalBlob as _ExternalBlob, LoveLanguage as _LoveLanguage, LoveLanguageRanking as _LoveLanguageRanking, LoveLanguagesQuizResult as _LoveLanguagesQuizResult, PairingResult as _PairingResult, PartnerQuizState as _PartnerQuizState, RitualEntryView as _RitualEntryView, RitualPrompt as _RitualPrompt, RitualResponse as _RitualResponse, SharedPhoto as _SharedPhoto, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkPairingCode(arg0: bigint): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPairingCode(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPairingCode(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearLoveLanguagesQuizResults(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLoveLanguagesQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLoveLanguagesQuizResults();
            return result;
        }
    }
    async completePairing(arg0: bigint): Promise<PairingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.completePairing(arg0);
                return from_candid_PairingResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePairing(arg0);
            return from_candid_PairingResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPairingCode(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPairingCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPairingCode();
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async fetchPrompts(): Promise<Array<RitualPrompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchPrompts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchPrompts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBadgeMilestones(): Promise<BadgeMilestoneResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getBadgeMilestones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBadgeMilestones();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCombinedQuizResultState(): Promise<CombinedQuizResultState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombinedQuizResultState();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombinedQuizResultState();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRitual(): Promise<RitualPrompt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRitual();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRitual();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsightsData(): Promise<InsighsDataExtendedResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsightsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsightsData();
            return result;
        }
    }
    async getLoveLanguageQuizResult(): Promise<LoveLanguagesQuizResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoveLanguageQuizResult();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoveLanguageQuizResult();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerQuizState(arg0: UserId): Promise<PartnerQuizState> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerQuizState(arg0);
                return from_candid_PartnerQuizState_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerQuizState(arg0);
            return from_candid_PartnerQuizState_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoto(arg0: string): Promise<SharedPhoto | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoto(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoto(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotosByUser(arg0: UserId): Promise<Array<SharedPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByUser(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByUser(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromptsByLoveLanguage(arg0: LoveLanguage): Promise<Array<RitualPrompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptsByLoveLanguage(to_candid_LoveLanguage_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptsByLoveLanguage(to_candid_LoveLanguage_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRitualHistory(arg0: bigint): Promise<Array<RitualEntryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRitualHistory(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRitualHistory(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRitualStatus(): Promise<CanonicalPartnerRitualStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRitualStatus();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRitualStatus();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeUserProfile(arg0: string, arg1: UserId | null): Promise<UserId> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUserProfile(arg0, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUserProfile(arg0, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveLoveLanguageQuizResults(arg0: LoveLanguagesQuizResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLoveLanguageQuizResults(to_candid_LoveLanguagesQuizResult_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLoveLanguageQuizResults(to_candid_LoveLanguagesQuizResult_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRitualResponse(arg0: DailyRitualInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRitualResponse(to_candid_DailyRitualInput_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRitualResponse(to_candid_DailyRitualInput_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadPhoto(arg0: ExternalBlob, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(await to_candid_ExternalBlob_n65(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_CombinedQuizResultState_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CombinedQuizResultState): CombinedQuizResultState {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LoveLanguageRanking_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoveLanguageRanking): LoveLanguageRanking {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_LoveLanguage_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoveLanguage): LoveLanguage {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LoveLanguagesQuizResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoveLanguagesQuizResult): LoveLanguagesQuizResult {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PairingResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PairingResult): PairingResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PartnerQuizState_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartnerQuizState): PartnerQuizState {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RitualEntryView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RitualEntryView): RitualEntryView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_RitualPrompt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RitualPrompt): RitualPrompt {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RitualResponse_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RitualResponse): RitualResponse {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_SharedPhoto_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedPhoto): Promise<SharedPhoto> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LoveLanguage]): LoveLanguage | null {
    return value.length === 0 ? null : from_candid_LoveLanguage_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CombinedQuizResultState]): CombinedQuizResultState | null {
    return value.length === 0 ? null : from_candid_CombinedQuizResultState_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LoveLanguagesQuizResult]): LoveLanguagesQuizResult | null {
    return value.length === 0 ? null : from_candid_LoveLanguagesQuizResult_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RitualPrompt]): RitualPrompt | null {
    return value.length === 0 ? null : from_candid_RitualPrompt_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SharedPhoto]): Promise<SharedPhoto | null> {
    return value.length === 0 ? null : await from_candid_SharedPhoto_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanonicalPartnerRitualStatus]): CanonicalPartnerRitualStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    text: string;
    loveLanguage: [] | [_LoveLanguage];
}): {
    id: bigint;
    text: string;
    loveLanguage?: LoveLanguage;
} {
    return {
        id: value.id,
        text: value.text,
        loveLanguage: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.loveLanguage))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
    partnerId: [] | [Principal];
    isFirstUser: boolean;
}): {
    name: string;
    role: UserRole;
    partnerId?: Principal;
    isFirstUser: boolean;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        partnerId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.partnerId)),
        isFirstUser: value.isFirstUser
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    callerResults: [] | [_LoveLanguagesQuizResult];
    partnerCompleted: boolean;
    partnerResults: [] | [_LoveLanguagesQuizResult];
    callerCompleted: boolean;
}): {
    callerResults?: LoveLanguagesQuizResult;
    partnerCompleted: boolean;
    partnerResults?: LoveLanguagesQuizResult;
    callerCompleted: boolean;
} {
    return {
        callerResults: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.callerResults)),
        partnerCompleted: value.partnerCompleted,
        partnerResults: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.partnerResults)),
        callerCompleted: value.callerCompleted
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rankings: Array<_LoveLanguageRanking>;
    completionTime: _Time;
    userId: _UserId;
}): {
    rankings: Array<LoveLanguageRanking>;
    completionTime: Time;
    userId: UserId;
} {
    return {
        rankings: from_candid_vec_n32(_uploadFile, _downloadFile, value.rankings),
        completionTime: value.completionTime,
        userId: value.userId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: number;
    language: _LoveLanguage;
}): {
    score: number;
    language: LoveLanguage;
} {
    return {
        score: value.score,
        language: from_candid_LoveLanguage_n17(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partnerCompleted: boolean;
    partnerResults: [] | [_LoveLanguagesQuizResult];
}): {
    partnerCompleted: boolean;
    partnerResults?: LoveLanguagesQuizResult;
} {
    return {
        partnerCompleted: value.partnerCompleted,
        partnerResults: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.partnerResults))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: _UserId;
    blob: _ExternalBlob;
    name: string;
    timestamp: _Time;
}): Promise<{
    id: string;
    owner: UserId;
    blob: ExternalBlob;
    name: string;
    timestamp: Time;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        timestamp: value.timestamp
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    responses: Array<_RitualResponse>;
    loveLanguageFocus: [] | [_LoveLanguage];
    date: bigint;
    prompt: _RitualPrompt;
}): {
    responses: Array<RitualResponse>;
    loveLanguageFocus?: LoveLanguage;
    date: bigint;
    prompt: RitualPrompt;
} {
    return {
        responses: from_candid_vec_n48(_uploadFile, _downloadFile, value.responses),
        loveLanguageFocus: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.loveLanguageFocus)),
        date: value.date,
        prompt: from_candid_RitualPrompt_n14(_uploadFile, _downloadFile, value.prompt)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    text: [] | [string];
    emoji: [] | [string];
    photoId: [] | [string];
}): {
    userId: UserId;
    text?: string;
    emoji?: string;
    photoId?: string;
} {
    return {
        userId: value.userId,
        text: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.text)),
        emoji: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.emoji)),
        photoId: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.photoId))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qualityTime: null;
} | {
    receivingGifts: null;
} | {
    actsOfService: null;
} | {
    wordsOfAffirmation: null;
} | {
    physicalTouch: null;
}): LoveLanguage {
    return "qualityTime" in value ? LoveLanguage.qualityTime : "receivingGifts" in value ? LoveLanguage.receivingGifts : "actsOfService" in value ? LoveLanguage.actsOfService : "wordsOfAffirmation" in value ? LoveLanguage.wordsOfAffirmation : "physicalTouch" in value ? LoveLanguage.physicalTouch : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RitualPrompt>): Array<RitualPrompt> {
    return value.map((x)=>from_candid_RitualPrompt_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoveLanguageRanking>): Array<LoveLanguageRanking> {
    return value.map((x)=>from_candid_LoveLanguageRanking_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SharedPhoto>): Promise<Array<SharedPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SharedPhoto_n39(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RitualEntryView>): Array<RitualEntryView> {
    return value.map((x)=>from_candid_RitualEntryView_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RitualResponse>): Array<RitualResponse> {
    return value.map((x)=>from_candid_RitualResponse_n49(_uploadFile, _downloadFile, x));
}
function to_candid_DailyRitualInput_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyRitualInput): _DailyRitualInput {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LoveLanguageRanking_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveLanguageRanking): _LoveLanguageRanking {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_LoveLanguage_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveLanguage): _LoveLanguage {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_LoveLanguagesQuizResult_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveLanguagesQuizResult): _LoveLanguagesQuizResult {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    partnerId?: Principal;
    isFirstUser: boolean;
}): {
    name: string;
    role: _UserRole;
    partnerId: [] | [Principal];
    isFirstUser: boolean;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n56(_uploadFile, _downloadFile, value.role),
        partnerId: value.partnerId ? candid_some(value.partnerId) : candid_none(),
        isFirstUser: value.isFirstUser
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rankings: Array<LoveLanguageRanking>;
    completionTime: Time;
    userId: UserId;
}): {
    rankings: Array<_LoveLanguageRanking>;
    completionTime: _Time;
    userId: _UserId;
} {
    return {
        rankings: to_candid_vec_n60(_uploadFile, _downloadFile, value.rankings),
        completionTime: value.completionTime,
        userId: value.userId
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: number;
    language: LoveLanguage;
}): {
    score: number;
    language: _LoveLanguage;
} {
    return {
        score: value.score,
        language: to_candid_LoveLanguage_n43(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text?: string;
    emoji?: string;
    photoId?: string;
}): {
    text: [] | [string];
    emoji: [] | [string];
    photoId: [] | [string];
} {
    return {
        text: value.text ? candid_some(value.text) : candid_none(),
        emoji: value.emoji ? candid_some(value.emoji) : candid_none(),
        photoId: value.photoId ? candid_some(value.photoId) : candid_none()
    };
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveLanguage): {
    qualityTime: null;
} | {
    receivingGifts: null;
} | {
    actsOfService: null;
} | {
    wordsOfAffirmation: null;
} | {
    physicalTouch: null;
} {
    return value == LoveLanguage.qualityTime ? {
        qualityTime: null
    } : value == LoveLanguage.receivingGifts ? {
        receivingGifts: null
    } : value == LoveLanguage.actsOfService ? {
        actsOfService: null
    } : value == LoveLanguage.wordsOfAffirmation ? {
        wordsOfAffirmation: null
    } : value == LoveLanguage.physicalTouch ? {
        physicalTouch: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LoveLanguageRanking>): Array<_LoveLanguageRanking> {
    return value.map((x)=>to_candid_LoveLanguageRanking_n61(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
